@startuml Routes

title View Routes Sequence Diagram
actor Users
Users -> LP: Clicks on "Login" button
LP -> App: Sends user credentials
App -> LP: Returns acknowledgement of credential
participant "Routes" as Routes

App -> Routes: View Routes
Routes -> App: Return Routes view
@enduml