@startuml Shifts

title View Bus Schedule Sequence Diagram
actor Users 
Users -> LP: Clicks on "Login" button
LP -> App: Sends user credentials
App -> LP: Returns acknowledgement of credential
participant "Shifts" as Shifts

App -> Shifts: View Shifts
Shifts -> App: Return Shifts view
@enduml