@startuml Shifts

title Edit Shifts Sequence Diagram
actor Admin
Admin -> LP: Clicks on "Login" button
LP -> App: Sends user credentials
App -> LP: Returns acknowledgement of credential
participant "Shifts" as Shifts

App -> Shifts: View Shifts
Shifts -> App: Return Shifts view

App -> Shifts: Edit Designated Shift/Shifts
Shifts -> App: Return Shifts view

@enduml