@startuml Login
title Login Page Sequence Diagram
actor Admin

participant "Login Page" as LP

Admin -> LP: Clicks on "Login" button
LP -> App: Sends user credentials
App -> LP: Returns acknowledgement of credentials
        
@enduml