@startuml Login
title Login Page Sequence Diagram
actor Admin

participant "Login Page" as LP

Admin -> LP: Clicks on "Login" button
LP -> App: Sends user credentials
App -> LP: Returns acknowledgement of credentials
        
@enduml


' @startuml

' actor Admin


' participant "Login Page" as LP
' participant "App" as App

' User -> LP: Clicks on "Login" button
' LP -> App: Sends user credentials
' App -> LP: Returns acknowledgement of credentials
' alt User is an admin
'     LP -> App: Sends "admin" role
'     App -> LP: Returns "Welcome, Admin" message
' else User is a regular user
'     LP -> App: Sends "user" role
'     App -> LP: Returns "Welcome, User" message
' end

' @enduml