@startuml Landmarks

title Delete LandMarks Sequence Diagram 
actor Admin
Admin -> LP: Clicks on "Login" button
LP -> App: Sends user credentials
App -> LP: Returns acknowledgement of credential
participant "Landmarks" as Landmarks

App -> Landmarks: View Landmarks
Landmarks -> App: Return Landmarks view

App -> Landmarks: Add Landmarks
Landmarks -> App: Return Landmarks view
@enduml