@startuml Admin
title ADMIN FLOWCHART
left to right direction 

actor Admin

package Application{

  usecase "Login" as [loginpage]

  'Routes
  [loginpage]..> [routes]
  [routes]..> (Delete)
  [routes] ..> (Edit)
  [routes]..> (Add)
  [routes]..> (View)


  'Landslots
  [loginpage]..> [landmarks]
  [landmarks]..> [Delete]
  [landmarks]..> [Edit]
  [landmarks]..> [Add]
  [landmarks]..> (View)


  'Time Slots
  [loginpage]..> [time slot]
  [time slot]..> [Delete]
  [time slot]..> [Edit]
  [time slot]..> [Add]



  'Buses
  [loginpage]..> [buses]
  [buses]..> [Delete]
  [buses]..> [Edit]
  [buses]..> [Add]

  'Analytics report
  [loginpage]..> [Dashboard]
  [Dashboard]..> [Users, Drivers, Both]
  [Users, Drivers, Both]..>(KPIs, backup)

  

  'Maintainance
  [loginpage]..> [Maintainance]
  [Maintainance]..> (Security, Backup, Restore, Cleanup)

  'users
  [loginpage]..> [Users]
  [Users]..> [Add]
  [Users]..> [Edit]
  [Users]..>[View]
  
  
  'Drivers
  [loginpage]..> [Drivers]
  [Drivers]..>[Contact Drivers]
  [Contact Drivers]..> (name, phone number, leaves taken)
  [Drivers]..> [Edit]
  [loginpage]..> [Support]
  [Support]..> (View)


  'General Maps
  [loginpage]..> [Maps]
  [Maps]..>[Enter your location]
  [Enter your location]..>[Routes]
  [Routes]..>(R1, R2, R3, R4)

}
@enduml

