@startuml

actor Drivers
participant "Login Page" as LP
participant "Application" as App
participant "Personal Profile" as PP
participant "Bus Schedule" as BS
participant "Maps" as Maps
participant "Dashboard" as DS

Drivers -> LP: Clicks on "Login" button
LP -> App: Sends user credentials
App -> LP: Returns acknowledgement of credentials

Drivers -> PP: View personal profile
PP -> Drivers: Returns personal profile

Drivers -> BS: View bus schedule
BS -> Drivers: Returns bus schedule

Drivers -> Maps: View map of routes and landmarks
Maps -> Drivers: Returns map

Drivers -> DS: View dashboard
DS -> Drivers: Returns dashboard

@enduml