@startuml Drivers
title DRIVERS FLOWCHART
left to right direction 


actor Drivers

package Application{
  usecase "Login" as [loginpage]

    'Personal Profile
    [loginpage]..> [Personal Profile]
    [Personal Profile]..> (View)

    
    'Bus Schedule 
    [loginpage]..> [Bus Schedule]
    [Bus Schedule]..> [View]

    'Maps
    [loginpage]..> [Maps]
    [Maps]..> [Routes] 

    'Dashboard
    [loginpage]..> [Dashboard]
    [Dashboard]..> (No of Trips)
    }

    Drivers --> loginpage

    @enduml

